// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    public class YodaClockDbContext : DbContext, IYodaClockDbContext
    {
        public YodaClockDbContext()
        {
        }

        public YodaClockDbContext(DbContextOptions<YodaClockDbContext> options)
            : base(options)
        {
        }

        public DbSet<DbResponse> DbResponses { get; set; } // DbResponse
        public DbSet<Exercise> Exercises { get; set; } // Exercise
        public DbSet<LuxResponse> LuxResponses { get; set; } // LuxResponse
        public DbSet<Meal> Meals { get; set; } // Meal
        public DbSet<Nap> Naps { get; set; } // Nap
        public DbSet<Plan> Plans { get; set; } // Plan
        public DbSet<PlanMealTime> PlanMealTimes { get; set; } // PlanMealTime
        public DbSet<Product> Products { get; set; } // Product
        public DbSet<User> Users { get; set; } // User
        public DbSet<UserEnvironment> UserEnvironments { get; set; } // UserEnvironment
        public DbSet<UserMealExercise> UserMealExercises { get; set; } // UserMealExercise
        public DbSet<UserNap> UserNaps { get; set; } // UserNap
        public DbSet<UserPrecondition> UserPreconditions { get; set; } // UserPrecondition
        public DbSet<UserProductMeal> UserProductMeals { get; set; } // UserProductMeal

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new DbResponseConfiguration());
            modelBuilder.ApplyConfiguration(new ExerciseConfiguration());
            modelBuilder.ApplyConfiguration(new LuxResponseConfiguration());
            modelBuilder.ApplyConfiguration(new MealConfiguration());
            modelBuilder.ApplyConfiguration(new NapConfiguration());
            modelBuilder.ApplyConfiguration(new PlanConfiguration());
            modelBuilder.ApplyConfiguration(new PlanMealTimeConfiguration());
            modelBuilder.ApplyConfiguration(new ProductConfiguration());
            modelBuilder.ApplyConfiguration(new UserConfiguration());
            modelBuilder.ApplyConfiguration(new UserEnvironmentConfiguration());
            modelBuilder.ApplyConfiguration(new UserMealExerciseConfiguration());
            modelBuilder.ApplyConfiguration(new UserNapConfiguration());
            modelBuilder.ApplyConfiguration(new UserPreconditionConfiguration());
            modelBuilder.ApplyConfiguration(new UserProductMealConfiguration());
        }

    }
}
// </auto-generated>

