// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    // Meal
    public class Meal
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public int PlanId { get; set; } // PlanId

        // Reverse navigation

        /// <summary>
        /// Child PlanMealTimes where [PlanMealTime].[MealId] point to this entity (FK_PlanMealTime_Meal)
        /// </summary>
        public virtual ICollection<PlanMealTime> PlanMealTimes { get; set; } // PlanMealTime.FK_PlanMealTime_Meal

        /// <summary>
        /// Child UserMealExercises where [UserMealExercise].[MealId] point to this entity (FK_UserMeaExerise_Meal)
        /// </summary>
        public virtual ICollection<UserMealExercise> UserMealExercises { get; set; } // UserMealExercise.FK_UserMeaExerise_Meal

        /// <summary>
        /// Child UserProductMeals where [UserProductMeal].[MealId] point to this entity (FK_UserProductMeal_Meal)
        /// </summary>
        public virtual ICollection<UserProductMeal> UserProductMeals { get; set; } // UserProductMeal.FK_UserProductMeal_Meal

        // Foreign keys

        /// <summary>
        /// Parent Plan pointed by [Meal].([PlanId]) (FK_Meal_Plan)
        /// </summary>
        public virtual Plan Plan { get; set; } // FK_Meal_Plan

        public Meal()
        {
            PlanMealTimes = new List<PlanMealTime>();
            UserMealExercises = new List<UserMealExercise>();
            UserProductMeals = new List<UserProductMeal>();
        }
    }

}
// </auto-generated>

