// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    // Nap
    public class Nap
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public int PlanId { get; set; } // PlanId
        public decimal Percentage { get; set; } // Percentage

        // Reverse navigation

        /// <summary>
        /// Child UserNaps where [UserNap].[NapId] point to this entity (FK_UserNap_Nap)
        /// </summary>
        public virtual ICollection<UserNap> UserNaps { get; set; } // UserNap.FK_UserNap_Nap

        // Foreign keys

        /// <summary>
        /// Parent Plan pointed by [Nap].([PlanId]) (FK_Nap_Plan)
        /// </summary>
        public virtual Plan Plan { get; set; } // FK_Nap_Plan

        public Nap()
        {
            UserNaps = new List<UserNap>();
        }
    }

}
// </auto-generated>

