// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    // Plan
    public class Plan
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public decimal ExercisePercentage { get; set; } // ExercisePercentage
        public int ExcerciseTime { get; set; } // ExcerciseTime
        public decimal Carb { get; set; } // Carb
        public decimal Fat { get; set; } // Fat
        public decimal Protein { get; set; } // Protein
        public int SleepDuration { get; set; } // SleepDuration

        // Reverse navigation

        /// <summary>
        /// Child Exercises where [Exercise].[PlanId] point to this entity (FK_Exercise_Plan)
        /// </summary>
        public virtual ICollection<Exercise> Exercises { get; set; } // Exercise.FK_Exercise_Plan

        /// <summary>
        /// Child Meals where [Meal].[PlanId] point to this entity (FK_Meal_Plan)
        /// </summary>
        public virtual ICollection<Meal> Meals { get; set; } // Meal.FK_Meal_Plan

        /// <summary>
        /// Child Naps where [Nap].[PlanId] point to this entity (FK_Nap_Plan)
        /// </summary>
        public virtual ICollection<Nap> Naps { get; set; } // Nap.FK_Nap_Plan

        /// <summary>
        /// Child PlanMealTimes where [PlanMealTime].[PlanId] point to this entity (FK_PlanMealTime_Plan)
        /// </summary>
        public virtual ICollection<PlanMealTime> PlanMealTimes { get; set; } // PlanMealTime.FK_PlanMealTime_Plan

        /// <summary>
        /// Child Products where [Product].[PlanId] point to this entity (FK_Product_Plan)
        /// </summary>
        public virtual ICollection<Product> Products { get; set; } // Product.FK_Product_Plan

        /// <summary>
        /// Child Users where [User].[PlanId] point to this entity (FK_User_Plan)
        /// </summary>
        public virtual ICollection<User> Users { get; set; } // User.FK_User_Plan

        public Plan()
        {
            Exercises = new List<Exercise>();
            Meals = new List<Meal>();
            Naps = new List<Nap>();
            PlanMealTimes = new List<PlanMealTime>();
            Products = new List<Product>();
            Users = new List<User>();
        }
    }

}
// </auto-generated>

