// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    // Product
    public class Product
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public decimal Carb { get; set; } // Carb
        public decimal Fat { get; set; } // Fat
        public decimal Protein { get; set; } // Protein
        public int PlanId { get; set; } // PlanId

        // Reverse navigation

        /// <summary>
        /// Child UserProductMeals where [UserProductMeal].[ProductId] point to this entity (FK_UserProductMeal_Product)
        /// </summary>
        public virtual ICollection<UserProductMeal> UserProductMeals { get; set; } // UserProductMeal.FK_UserProductMeal_Product

        // Foreign keys

        /// <summary>
        /// Parent Plan pointed by [Product].([PlanId]) (FK_Product_Plan)
        /// </summary>
        public virtual Plan Plan { get; set; } // FK_Product_Plan

        public Product()
        {
            UserProductMeals = new List<UserProductMeal>();
        }
    }

}
// </auto-generated>

