// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    // UserEnvironment
    public class UserEnvironment
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public decimal Noise { get; set; } // Noise
        public decimal Illumination { get; set; } // Illumination

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [UserEnvironment].([UserId]) (FK_UserEnvironment_User)
        /// </summary>
        public virtual User User { get; set; } // FK_UserEnvironment_User
    }

}
// </auto-generated>

