// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    // User
    public class User
    {
        public int Id { get; set; } // Id (Primary key)
        public int PlanId { get; set; } // PlanId
        public string Username { get; set; } // Username (length: 100)
        public string Token { get; set; } // Token (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child UserEnvironments where [UserEnvironment].[UserId] point to this entity (FK_UserEnvironment_User)
        /// </summary>
        public virtual ICollection<UserEnvironment> UserEnvironments { get; set; } // UserEnvironment.FK_UserEnvironment_User

        /// <summary>
        /// Child UserMealExerises where [UserMealExerise].[UserId] point to this entity (FK_UserMealExerise_User)
        /// </summary>
        public virtual ICollection<UserMealExercise> UserMealExercises { get; set; } // UserMealExerise.FK_UserMealExerise_User

        /// <summary>
        /// Child UserNaps where [UserNap].[UserId] point to this entity (FK_UserNap_User)
        /// </summary>
        public virtual ICollection<UserNap> UserNaps { get; set; } // UserNap.FK_UserNap_User

        /// <summary>
        /// Child UserPreconditions where [UserPrecondition].[UserId] point to this entity (FK_UserPrecondition_User)
        /// </summary>
        public virtual ICollection<UserPrecondition> UserPreconditions { get; set; } // UserPrecondition.FK_UserPrecondition_User

        /// <summary>
        /// Child UserProductMeals where [UserProductMeal].[UserId] point to this entity (FK_UserProductMeal_User)
        /// </summary>
        public virtual ICollection<UserProductMeal> UserProductMeals { get; set; } // UserProductMeal.FK_UserProductMeal_User

        // Foreign keys

        /// <summary>
        /// Parent Plan pointed by [User].([PlanId]) (FK_User_Plan)
        /// </summary>
        public virtual Plan Plan { get; set; } // FK_User_Plan

        public User()
        {
            UserEnvironments = new List<UserEnvironment>();
            UserMealExercises = new List<UserMealExercise>();
            UserNaps = new List<UserNap>();
            UserPreconditions = new List<UserPrecondition>();
            UserProductMeals = new List<UserProductMeal>();
        }
    }

}
// </auto-generated>

