// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    // UserNap
    public class UserNap
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int NapId { get; set; } // NapId
        public DateTime Timestamp { get; set; } // Timestamp

        // Foreign keys

        /// <summary>
        /// Parent Nap pointed by [UserNap].([NapId]) (FK_UserNap_Nap)
        /// </summary>
        public virtual Nap Nap { get; set; } // FK_UserNap_Nap

        /// <summary>
        /// Parent User pointed by [UserNap].([UserId]) (FK_UserNap_User)
        /// </summary>
        public virtual User User { get; set; } // FK_UserNap_User
    }

}
// </auto-generated>

