// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace YodaClock.DataContext
{
    // UserMealExercise
    public class UserMealExercise
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int MealId { get; set; } // MealId
        public int ExerciseId { get; set; } // ExerciseId
        public bool Ate { get; set; } // Ate
        public int Time { get; set; } // Time
        public DateTime Timestamp { get; set; } // Timestamp

        // Foreign keys

        /// <summary>
        /// Parent Exercise pointed by [UserMealExercise].([ExerciseId]) (FK_UserMealExerise_Exercise)
        /// </summary>
        public virtual Exercise Exercise { get; set; } // FK_UserMealExerise_Exercise

        /// <summary>
        /// Parent Meal pointed by [UserMealExercise].([MealId]) (FK_UserMeaExerise_Meal)
        /// </summary>
        public virtual Meal Meal { get; set; } // FK_UserMeaExerise_Meal

        /// <summary>
        /// Parent User pointed by [UserMealExercise].([UserId]) (FK_UserMealExerise_User)
        /// </summary>
        public virtual User User { get; set; } // FK_UserMealExerise_User
    }

}
// </auto-generated>

