// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YodaClock.DataContext
{
    // LuxResponse
    public class LuxResponseConfiguration : IEntityTypeConfiguration<LuxResponse>
    {
        public void Configure(EntityTypeBuilder<LuxResponse> builder)
        {
            builder.ToTable("LuxResponse", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_LuxResponse").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Lux).HasColumnName(@"Lux").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Percentage).HasColumnName(@"Percentage").HasColumnType("decimal(18,2)").IsRequired();
        }
    }

}
// </auto-generated>

