// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YodaClock.DataContext
{
    // PlanMealTime
    public class PlanMealTimeConfiguration : IEntityTypeConfiguration<PlanMealTime>
    {
        public void Configure(EntityTypeBuilder<PlanMealTime> builder)
        {
            builder.ToTable("PlanMealTime", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_PlanMealTime").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.PlanId).HasColumnName(@"PlanId").HasColumnType("int").IsRequired();
            builder.Property(x => x.MealId).HasColumnName(@"MealId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Percentage).HasColumnName(@"Percentage").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Start).HasColumnName(@"Start").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.End).HasColumnName(@"End").HasColumnType("datetime").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Plan).WithMany(b => b.PlanMealTimes).HasForeignKey(c => c.PlanId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_PlanMealTime_Plan");
        }
    }

}
// </auto-generated>

