// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YodaClock.DataContext
{
    // Plan
    public class PlanConfiguration : IEntityTypeConfiguration<Plan>
    {
        public void Configure(EntityTypeBuilder<Plan> builder)
        {
            builder.ToTable("Plan", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Plan").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.ExercisePercentage).HasColumnName(@"ExercisePercentage").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.ExcerciseTime).HasColumnName(@"ExcerciseTime").HasColumnType("int").IsRequired();
            builder.Property(x => x.Carb).HasColumnName(@"Carb").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Fat).HasColumnName(@"Fat").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Protein).HasColumnName(@"Protein").HasColumnType("decimal(18,2)").IsRequired();
        }
    }

}
// </auto-generated>

