// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YodaClock.DataContext
{
    // UserEnvironment
    public class UserEnvironmentConfiguration : IEntityTypeConfiguration<UserEnvironment>
    {
        public void Configure(EntityTypeBuilder<UserEnvironment> builder)
        {
            builder.ToTable("UserEnvironment", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_UserEnvironment").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Noise).HasColumnName(@"Noise").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Illumination).HasColumnName(@"Illumination").HasColumnType("decimal(18,2)").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.User).WithMany(b => b.UserEnvironments).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UserEnvironment_User");
        }
    }

}
// </auto-generated>

