// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YodaClock.DataContext
{
    // UserProductMeal
    public class UserProductMealConfiguration : IEntityTypeConfiguration<UserProductMeal>
    {
        public void Configure(EntityTypeBuilder<UserProductMeal> builder)
        {
            builder.ToTable("UserProductMeal", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_UserProductMeal").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            builder.Property(x => x.ProductId).HasColumnName(@"ProductId").HasColumnType("int").IsRequired();
            builder.Property(x => x.MealId).HasColumnName(@"MealId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Amount).HasColumnName(@"Amount").HasColumnType("int").IsRequired();
            builder.Property(x => x.Timestamp).HasColumnName(@"Timestamp").HasColumnType("datetime").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Meal).WithMany(b => b.UserProductMeals).HasForeignKey(c => c.MealId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UserProductMeal_Meal");
            builder.HasOne(a => a.Product).WithMany(b => b.UserProductMeals).HasForeignKey(c => c.ProductId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UserProductMeal_Product");
            builder.HasOne(a => a.User).WithMany(b => b.UserProductMeals).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UserProductMeal_User");
        }
    }

}
// </auto-generated>

