// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YodaClock.DataContext
{
    // UserPrecondition
    public class UserPreconditionConfiguration : IEntityTypeConfiguration<UserPrecondition>
    {
        public void Configure(EntityTypeBuilder<UserPrecondition> builder)
        {
            builder.ToTable("UserPrecondition", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_UserPrecondition").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            builder.Property(x => x.SleepDuration).HasColumnName(@"SleepDuration").HasColumnType("int").IsRequired();
            builder.Property(x => x.SleepInterruptions).HasColumnName(@"SleepInterruptions").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.User).WithMany(b => b.UserPreconditions).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UserPrecondition_User");
        }
    }

}
// </auto-generated>

